name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build_and_deploy:    
    runs-on: ubuntu-20.04
    name: Build and deploy to Azure Static Web Apps
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SALMON_FOREST_027350010 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"          
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/e2e-examples/server/assets" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory

  test:
    timeout-minutes: 60
    needs: build_and_deploy
    runs-on: ubuntu-20.04
    container: mcr.microsoft.com/playwright:focal
    environment:
      name: test
      url: https://demo.marcusfelling.com/
    env:
      SITE_URL: https://demo.marcusfelling.com/ # Playwright tests use this env var    
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm ci     

      - name: Run Playwright Tests        
        continue-on-error: false
        working-directory: e2e-examples
        run: |   
          HOME=/root npx playwright test --config playwright.config.ts --reporter=html

      - uses: actions/upload-artifact@v2
        name: Upload HTML report
        if: always()
        with:
          name: playwright-test-report
          path: e2e-examples/playwright-report/index.html

      - uses: actions/upload-artifact@v2
        name: If failure, upload trace.zip to troubleshoot
        if: failure()
        with:
          name: playwright-test-trace
          path: e2e-examples/test-results/
